//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicApi.Items.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedIdentityErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedIdentityErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicApi.Items.Resources.LocalizedIdentityErrorMessages", typeof(LocalizedIdentityErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eş-zamanlama hatası..
        /// </summary>
        internal static string ConcurrencyFailure
        {
            get
            {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı yönetim sistemi hatası..
        /// </summary>
        internal static string DefaultIdentityError
        {
            get
            {
                return ResourceManager.GetString("DefaultIdentityError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Eposta adresi &apos;{0}&apos; önceden kayıtlıdır..
        /// </summary>
        internal static string DuplicateEmail
        {
            get
            {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rol adı &apos;{0}&apos; önceden kayıtlıdır..
        /// </summary>
        internal static string DuplicateRoleName
        {
            get
            {
                return ResourceManager.GetString("DuplicateRoleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı &apos;{0}&apos; önceden kayıtlıdır..
        /// </summary>
        internal static string DuplicateUserName
        {
            get
            {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email adresi  &apos;{0}&apos; geçerli değildir..
        /// </summary>
        internal static string InvalidEmail
        {
            get
            {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rol adı &apos;{0}&apos; geçerli değildir..
        /// </summary>
        internal static string InvalidRoleName
        {
            get
            {
                return ResourceManager.GetString("InvalidRoleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Doğrulama kodu geçerli değildir..
        /// </summary>
        internal static string InvalidToken
        {
            get
            {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı &apos;{0}&apos; geçerli değildir..
        /// </summary>
        internal static string InvalidUserName
        {
            get
            {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bir harici giriş zaten bu hesaba bağlıdır..
        /// </summary>
        internal static string LoginAlreadyAssociated
        {
            get
            {
                return ResourceManager.GetString("LoginAlreadyAssociated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yazdığınız şifre hesabınızda kayıtlı olan şifre ile eşleşmiyor..
        /// </summary>
        internal static string PasswordMismatch
        {
            get
            {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre rakan içermelidir (0-9)..
        /// </summary>
        internal static string PasswordRequiresDigit
        {
            get
            {
                return ResourceManager.GetString("PasswordRequiresDigit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre küçük harf içermelidir (a-z)..
        /// </summary>
        internal static string PasswordRequiresLower
        {
            get
            {
                return ResourceManager.GetString("PasswordRequiresLower", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre harf-rakam olmayan karakterler içermelidir (! + , ? ...).
        /// </summary>
        internal static string PasswordRequiresNonAlphanumeric
        {
            get
            {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre en az &apos;{0}&apos; benzersiz karakter içermelidir..
        /// </summary>
        internal static string PasswordRequiresUniqueChars
        {
            get
            {
                return ResourceManager.GetString("PasswordRequiresUniqueChars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre büyük harf içermelidir (A-Z)..
        /// </summary>
        internal static string PasswordRequiresUpper
        {
            get
            {
                return ResourceManager.GetString("PasswordRequiresUpper", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Şifre en az &apos;{0}&apos; karakter uzunluğu olmalıdır..
        /// </summary>
        internal static string PasswordTooShort
        {
            get
            {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kurtarma kodu kullanılamadı..
        /// </summary>
        internal static string RecoveryCodeRedemptionFailed
        {
            get
            {
                return ResourceManager.GetString("RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının zaten bir şifresi vardır..
        /// </summary>
        internal static string UserAlreadyHasPassword
        {
            get
            {
                return ResourceManager.GetString("UserAlreadyHasPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının zaten &apos;{0}&apos; rolü vardır..
        /// </summary>
        internal static string UserAlreadyInRole
        {
            get
            {
                return ResourceManager.GetString("UserAlreadyInRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı kilidi aktif değildir..
        /// </summary>
        internal static string UserLockoutNotEnabled
        {
            get
            {
                return ResourceManager.GetString("UserLockoutNotEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının &apos;{0}&apos; rolü yoktur..
        /// </summary>
        internal static string UserNotInRole
        {
            get
            {
                return ResourceManager.GetString("UserNotInRole", resourceCulture);
            }
        }
    }
}
